### ISSUE TITLE
Translate add

### ISSUE THREAD

**Issue by ziceptor** [DosMike/VillagerShops#14]
https://github.com/DosMike/VillagerShops/blob/master/src/de/dosmike/sponge/vshop/StockItem.java

**75** desc.add(Text.of(TextColors.GREEN, "**Sell for:** ", TextColors.WHITE, String.format("%.2f", sellprice), cs, (item.getQuantity()>1? 

**92** desc.add(Text.of(TextColors.RED, "**Buy for:** ", TextColors.WHITE, String.format("%.2f", buyprice), cs, (item.getQuantity()>1?

**Comment by DosMike** [comment]
Thank you for the hint, I'll add it to the translations tomorrow
