### ISSUE TITLE
/vshop create minecraft:villager

### ISSUE THREAD

**Issue by ziceptor** [DosMike/VillagerShops#20]
Weird! I did not receive the character. There are no errors. The message about the successful creation of the store.

And again. How to create shops based on config (admin)? How to list all available stores (admin)? /vsop list <-- I would like to have

**Comment by ziceptor** [comment]
Hmm. Maybe it was due to the old language file.

**Comment by TheCoolTurtle** [comment]
I'm having this issue too

**Comment by DosMike** [comment]
I need more information to be able to help. What was the exact command you used? Where did you try to spawn in - near world spawn? Do you have any protective plugins that may prevent entity/mob spawning? Are you permitted to spawn entites/mobs in the area? Do you have command permissions? Do you like fish?

**Comment by ziceptor** [comment]
This behavior was to reboot the server. Fish is good! ;)

**Comment by DosMike** [comment]
So you mean everything works, until you reboot the server? also what sponge/Minecraft version do you use?

**Comment by ziceptor** [comment]
Works not until you reboot. And the problem was corrected after a reboot. Version I do not remember. But always they were the last.

**Comment by ziceptor** [comment]
At the moment works correctly

forge-1.12.2-14.23.1.2555-universal.jar
spongeforge-1.12.2-2555-7.0.0-BETA-2780.jar
VillagerShops.jar latest

**Comment by DosMike** [comment]
hm... I'll have to take a closer look. until that you should be able to use `/vshop save` followed by `/vshop reload` to to refresh all shops (so you don't have to restart the server)

**Comment by BrandHyde** [comment]
Always do /vshop save after ever edit. If you restart or reload the plugin before this it will overwrite everything you have done. /vshop save guarantees that the data will be saved to the config file!
