### ISSUE TITLE
/vshop add

### ISSUE THREAD

**Issue by ziceptor** [DosMike/VillagerShops#21]
/vshop add 10 15
add SellPrice = BuyPrice

**Comment by DosMike** [comment]
what?

**Comment by ziceptor** [comment]
the same value

**Comment by ziceptor** [comment]
equal

**Comment by DosMike** [comment]
but you can already do this, just type the same value twice?

**Comment by ziceptor** [comment]
Sorry for my English. I say that sometimes I enter different values for buy and sell, but they are the same. 
/vshop add 10 15 did value 15 15

**Comment by DosMike** [comment]
I will look into that
