### ISSUE TITLE
Can't figure out how to add a price

### ISSUE THREAD

**Issue by BrianMurrell** [DosMike/VillagerShops#23]
I've tried everything i can think of and i cannot set i price for a villager shops item, it just always says "buy price has no ~ or decimal." I'm so confused. Sorry if i am being a total noob

**Comment by DosMike** [comment]
you need to specify two price options: one is the price to buy for, one is the price to sell for. you can disable a option by typing ~ instead of a price, but one is required. e.g.: `/vshop add 15 30`
more information should be available with `/help vshop`
