### ISSUE TITLE
Cannot / don't know how to spawn a modded villager!

### ISSUE THREAD

**Issue by BrandHyde** [DosMike/VillagerShops#25]
The villagers from mods tie into the API of minecraft, so they don't have their own seperate ID's like a twilight creature, or a tinkers construct slime.
I tried --skin and came up empty!
![image](https://user-images.githubusercontent.com/34900612/34692869-8afa33be-f4b9-11e7-9182-1f000c93fd90.png)

There's some extra info hopefully someone can help me :)

**Comment by DosMike** [comment]
Ok, this was due to me using names instead of ID which of course are what should be used to support mods. Additionally to not using the Sponge registry. Should be fixed with the next update :)
