### ISSUE TITLE
Sell for: $nu -- LangSwitch not working?

### ISSUE THREAD

**Issue by Mike5357** [DosMike/VillagerShops#26]
https://gyazo.com/924ea6f30990e90c399e5f65b6c39f6c

I'm assuming this is an issue with LangSwitch not working properly, but went to download the latest version from the Ore page and received the error: Unexpected exception[NoSuchFileException: /home/ore/files/plugins/DosMike/LangSwitch/versions/1.1.2/LangSwitch.jar]

**Comment by Mike5357** [comment]
Found the github link for the download but still having an issue; will submit a new issue.

**Comment by Mike5357** [comment]
Found the download link from the github and made sure that LangSwitch is loaded with "/sponge plugins", but the villagershop is still showing "nu" instead of the price.

**Comment by DosMike** [comment]
what economy plugin are you using? I could imagine this is related to issue #24 and thus the price is invalid

**Comment by Mike5357** [comment]
I am using TotalEconomy 1.8.0-dev.3.

**Comment by DosMike** [comment]
I'm about to push a update.... would be cool if you could report back after trying that

**Comment by Mike5357** [comment]
Yup, works great now! Thanks
