### ISSUE TITLE
No option to set language

### ISSUE THREAD

**Issue by BrainStone** [DosMike/VillagerShops#31]
Currently there is no option in the config to set the langauge.

Also the default language files aren't generated.

**Comment by DosMike** [comment]
the default language is the server default, you can change that with a LangSwitch config (you need to create that manually, see the LangSwitch page) and language files are provided in the GitHub releases

**Comment by BrainStone** [comment]
I'd still like to be able to set the language per plugin.

**Comment by DosMike** [comment]
why would you want messages to display in mixed languages?
i mean you can set the language per player (LangSwitch's /language command)

**Comment by BrainStone** [comment]
Ah I see. I must've missed that!
