### ISSUE TITLE
vshop add command issue

### ISSUE THREAD

**Issue by DeadlyBladez** [DosMike/VillagerShops#33]
when i use /vshop add 1 - 
or /vshop add 1 ~ they both show up with the same error that is i have to have a number but i dont want it to show up on the bottom side of things i know i could do /vshop add 1 0 to make them sell for nothing but i would prefer it to not show up and - and ~ dont work for a price

**Comment by DeadlyBladez** [comment]
also im having issues with sell command buy command works just fine but i get an error when i try to sell to the shop guy ima guess its cause im using 1.10.2 and you dont support it anymore why not

**Comment by DosMike** [comment]
did you try to omit the other price like /vshop add ~ 1   
not to sound rude, but if you find a way to generate sparetime i'd gladly support older apis

**Comment by DeadlyBladez** [comment]
i tryed ~ and - and _ but none of them register main issue is you can buy them but sell dosnt seem to work so i was trying to make it not even show them in the sell option

**Comment by DosMike** [comment]
well if it's a bug I'll need the usual information, server version (you already told me), sponge version, plugin version, anything else related you can think of (e.g. logs if there's an error, pastebin or gist preferred)

**Comment by DeadlyBladez** [comment]
server 1.10.2 sponge and forge version 2477 plugin version 1.3.1 for api 6 i can spawn the villagers click on them to trade just cant sell to them the buy works so i tryed to set the sell to ~ to make it not show but if you could fix the sell that would be ok 2

**Comment by DosMike** [comment]
Ah, iirc that was a problem with inventory events or something like that.
This problem was fixed in later version. Again I know that you probably can't update the server but I just don't have the time to keep fixing it for old apis (especially with api 8 around the corner).
