### ISSUE TITLE
Fatal Error with non minecraft npc

### ISSUE THREAD

**Issue by Witchcrafter1** [DosMike/VillagerShops#34]
if the shop is with a npc from a mod or from sponge, like sponge:human, then every time a player interact with this shop it produce a fatal error: 
`[Fatal] Error executing taskjava.util.concurrent.ExecutionException: java.lang.NullPointerException	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2931]	at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003) [MinecraftServer.class:?]	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]Caused by: java.lang.NullPointerException	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:2529) ~[pa.class:?]	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) ~[PacketUtil.class:1.12.2-2611-7.1.0-BETA-2931]	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) ~[hv$1.class:?]	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]	... 7 more`

**Comment by DosMike** [comment]
Please post Server type, version, build; Sponge version; Plugin version; Mod list; The exact steps to reproduce the bug.
This Stacktrace does not mention my plugin once, how am I supposed to guess what's happening?

**Comment by Inscrutable** [comment]
This appears to be the same issue as #35 - it gives the error when interacting with a vshop. I'm getting this on the Sponge Community Server too, using SpongeVanilla 1.12.2-7.1.0-BETA-24, VillagerShops v1.8.1, LangSwitch v1.1.2, and a bunch of other plugins. Every time I modify a shop, it spits out the error above.

**Comment by DosMike** [comment]
Ok, so after playing around with the code I kinda got it.

This error seems to be caused by cancelling the InteractEntityEvent.Secondary event on Entities to do not have a default interaction. If I remove [the line](https://github.com/DosMike/VillagerShops/blob/bfdbb79fcf35185a55c382f3d4200d22359eae66/src/de/dosmike/sponge/vshop/EventListeners.java#L66) cancelling the event, all e.g. villager-type shops will display vanilla trades again.

@Inscrutable what do you think? Is this a sponge error?

**Comment by Witchcrafter1** [comment]
sry do u need still the infos how to reproduce?

**Comment by DosMike** [comment]
I'm not getting errors on recent versions of sponge, so fixed?
