### ISSUE TITLE
FATAL]: Error executing task (java.lang.NullPointerException)

### ISSUE THREAD

**Issue by ziceptor** [DosMike/VillagerShops#35]
/vshop create minecraft:player Инструменты
/vshop add bla-bla

Each time you interact with the store
https://gist.github.com/ziceptor/8dbb003a13a387655315dffef50f00e9#file-gistfile1-txt-L40

The goods are sold and bought.

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2931.jar

**Comment by ziceptor** [comment]
VillagerShops_1-8-1.zip

**Comment by ziceptor** [comment]
minecraft:player it was created with skin Steve
After re-entry he became Alex

**Comment by ziceptor** [comment]
config https://gist.github.com/ziceptor/e48ea7a274142f8a34d1c5cf65afe468

**Comment by DosMike** [comment]
I don't really know what's causing this but i poked around... hopefully it's fixed with the next release :s
