### ISSUE TITLE
No user was found

### ISSUE THREAD

**Issue by ziceptor** [DosMike/VillagerShops#36]
After starting the server
https://gist.github.com/ziceptor/437647ddb62213932c2bbf554a02f7c4

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2931.jar
VillagerShops_1-8-1.zip

**Comment by DosMike** [comment]
i can only guess this is related to your last ticket. steve is not a valis skin for human shops. skin expects either a uuid or a player name, from a player that has been on the server at least once

**Comment by ziceptor** [comment]
No. I didn't install the skin. The command was executed in this format: `/vshop create minecraft:player Инструменты.`

About skin I wrote, as I noticed that he spontaneously changed from a boy to a girl.

The player who created the store displays Steve. Alex is displayed to the other player. I just mentioned it because I saw this behavior.

No user was found:

/vshop create minecraft:player Инструменты
/vshop add bla-bla
/vshop save

restart server

After starting the server
https://gist.github.com/ziceptor/437647ddb62213932c2bbf554a02f7c4

**Comment by ziceptor** [comment]
config https://gist.github.com/ziceptor/e48ea7a274142f8a34d1c5cf65afe468

**Comment by DosMike** [comment]
well then I'll have to check that

**Comment by ziceptor** [comment]
any news

**Comment by ziceptor** [comment]
We still hope for a fix :)

**Comment by DosMike** [comment]
ok, so I can disable the error.

As for the skin, afaik this is randomly picked by the client so that'll stay random unless you --skin a sponge:human shop. i noticed that these skins seems to not load until the client reloaded the chunk (e.g. by moving far enough and back). also you can only user skins for players that visited the server at least once.
