### ISSUE TITLE
langswitch issue

### ISSUE THREAD

**Issue by Witchcrafter1** [DosMike/VillagerShops#38]
issue with this output in console:
how to fix?

20:35:53  [Info] [langswitch]: Missing translation shop.title
20:35:53  [Info] [langswitch]: Missing translation shop.item.buy.one
20:35:53  [Info] [langswitch]: Missing translation shop.item.sell.one

**Comment by DosMike** [comment]
Please install villager shops from the zip in the github releases. 
I can't upload translation files to ore if I wanted.
