### ISSUE TITLE
Error when use add command

### ISSUE THREAD

**Issue by StarchierOrb** [DosMike/VillagerShops#4]
Server Version:1.10.2

Error when use "/vshop add" command ....

Log:
07.08 22:21:46 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
07.08 22:21:46 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
07.08 22:21:46 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
07.08 22:21:46 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
07.08 22:21:46 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
07.08 22:21:46 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zhp000(MinecraftServer.java:3932) [MinecraftServer.class:?]
07.08 22:21:46 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:241) [SpongeImplHooks.class:1.10.2-2281-5.2.0-BETA-2464]
07.08 22:21:46 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
07.08 22:21:46 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
07.08 22:21:46 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
07.08 22:21:46 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
07.08 22:21:46 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjj000(SourceFile:539) [fl$1.class:?]
07.08 22:21:46 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) [PacketUtil.class:1.10.2-2281-5.2.0-BETA-2464]
07.08 22:21:46 [Server] INFO at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:162) [CauseTracker.class:1.10.2-2281-5.2.0-BETA-2464]
07.08 22:21:46 [Server] INFO at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-2281-5.2.0-BETA-2464]
07.08 22:21:46 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[im.class:?]
07.08 22:21:46 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[im.class:?]
07.08 22:21:46 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) ~[me.class:?]
07.08 22:21:46 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) ~[me.class:?]
07.08 22:21:46 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
07.08 22:21:46 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) ~[SpongeCommandManager.class:1.10.2-2281-5.2.0-BETA-2464]
07.08 22:21:46 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.10.2-2281-5.2.0-BETA-2464]
07.08 22:21:46 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359) ~[CommandSpec.class:1.10.2-2281-5.2.0-BETA-2464]
07.08 22:21:46 [Server] INFO at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:182) ~[ChildCommandElementExecutor.class:1.10.2-2281-5.2.0-BETA-2464]
07.08 22:21:46 [Server] INFO at de.dosmike.sponge.vshop.CommandRegistra$2.execute(CommandRegistra.java:156) ~[CommandRegistra$2.class:?]
07.08 22:21:46 [Server] INFO java.lang.NoSuchMethodError: org.spongepowered.api.item.inventory.ItemStack.getType()Lorg/spongepowered/api/item/ItemType;
07.08 22:21:46 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'vshop add 1 2' for source GCEntityPlayerMP['lzj'/321973, l='world', x=-1040.01, y=65.00, z=-4967.69]: org.spongepowered.api.item.inventory.ItemStack.getType()Lorg/spongepowered/api/item/ItemType;
07.08 22:21:46 [Server] Server thread/INFO [nucleus]: lzj ran the command: /vshop add 1 2
07.08 22:21:42 [Server] Server thread/ERROR  [Sponge]: Error occurred while executing command 'vshop add 1 1' for source GCEntityPlayerMP['lzj'/321973, l='world', x=-1040.06, y=65.00, z=-4967.65]:

**Comment by DosMike** [comment]
I'm using API 7 (1.12) where all the type functions where unified to be called `getType()` this is something that is not backwards compatible but I'll think about fixing it, just give me some time while I integrate LangSwitch into this...

**Comment by DosMike** [comment]
OK, so with a bit of playing around i got SpongeAPI 5 to not throw errors at me while testing VillagerShops, but trading items does not work for some reason - I can't look further into, API 5 is just old now and I'm not sure required stuff is implemented. It seems to runs fine on the SpongeAPI 6.1 stable branch tho.
