### ISSUE TITLE
The store is not available

### ISSUE THREAD

**Issue by ziceptor** [DosMike/VillagerShops#40]
If you exceed the limit of the goods, the store becomes unavailable.

/vshop add ~ x

> 27

Request:
I would like to be able to fill all slots for sale (purchase). You could choose the store type when you create it. Types: bay, sell, baysell.

**Comment by DosMike** [comment]
in order to be able to squash rows I'd have to mess with the code too much, sorry.
as for the 27+ items I'll add a limit, so at least the shop should stay accessible.

**Comment by DosMike** [comment]
Please reopen if issue persists
