### ISSUE TITLE
Not Deducting Funds

### ISSUE THREAD

**Issue by ZeroCool5254** [DosMike/VillagerShops#42]
I use TotalEconomy but when I buy or sell stuff from the shop, my balance has not been adjusted, is there something I did wrong or config I need to change?

**Comment by DosMike** [comment]
Please provide more information:

What version of VShop do you use?  
What version is your server running? (`/sponge version` is great for version information)   
What Items are effected?  
From player or admin shop?  

If you buy from your own playershop you're paying yourself resulting in a unchanged balance.

You can send me your shop config and the affected shops ids (`/vshop id`) if only a few are affected

**Comment by ZeroCool5254** [comment]
D'oh. stupid me. I realized that, like you said, testing my shop gives the money right back to me. I tested with a friend and it worked... 

Thanks for the info.
