### ISSUE TITLE
Target a specific Sponge API Version

### ISSUE THREAD

**Issue by phase** [DosMike/VillagerShops#44]
Hello! I noticed that your plugins on Ore don't have a version associated with their Sponge API tag. This is due to your `mcmod.info` files not containing a version with the `spongeapi` dependency:

https://github.com/DosMike/VillagerShops/blob/08489f230b8a1331cb8d7af767b323e013ad6197/res/mcmod.info#L9

Usually the version is automatically inserted with the Sponge Gradle Plugin, but since you're doing it manually you need to specify the Sponge API version you're using with the `pluginId@version` format, like

```json
"requiredMods": [ "langswitch@1.2", "spongeapi@7.0.0" ],
```

This will also make sure that the [Dependency sections](https://ore.spongepowered.org/DosMike/VillagerShops/versions/1.9) on your versions will contain the proper versions instead of "null".

**Comment by DosMike** [comment]
should be done with V1.9.1
