### ISSUE TITLE
Control clicking items in a shop allows you to just take the item

### ISSUE THREAD

**Issue by Krotain** [DosMike/VillagerShops#51]
No money gets taken from your account and the items seem to be fully usable. I recorded a video of me doing this.

https://www.youtube.com/watch?v=hxENKq7CBMA

forge-1.12.2-14.23.5.2768-universal.jar
spongeforge-1.12.2-2768-7.1.5-RC3506.jar
VillagerShops-1.9.1.jar

**Comment by DosMike** [comment]
do you have any mods on your server? if so, please send me the mod list

**Comment by Krotain** [comment]
[modlist.txt](https://github.com/DosMike/VillagerShops/files/2710899/modlist.txt)

All mods should be listed in this text file, it's ftb revelation but with a few added mods

**Comment by DosMike** [comment]
Alright, I hope you will understand that I can't check all 200+ mods. can you try if the problem still occurs without mousetweaks and or inventory tweaks? I suspect some mod is (even if only slightly) changing inventory behaviour, but without knowing the source I won't be able to fix it.

**Comment by Krotain** [comment]
Sorry it took so long to reply I had to wait till nobody was on to test this but I can confirm this issue does not occur when InventoryTweaks-1.63.jar is removed

**Comment by DosMike** [comment]
I currently am busy with uni again, but it was mentioned on discord, that invtweaks should not be installed server sided. seems to have fixed a similar issue for another plugin.
https://discordapp.com/channels/142425412096491520/142425521391665153/532087100753969161

Reading the discussion in the Sponge Discord I'm currently not sure I could fix this until I have some free time again. 

I would appreciate if you could report back if that's a acceptable solution (removing invtweaks server side) and everything still works.

**Comment by Krotain** [comment]
This does appear to work as far as I can tell thanks

**Comment by DosMike** [comment]
Alright, I'll change this issue to more info needed and will look at it some time in the future.
For now I'll add the information to the download pages.

**Comment by DosMike** [comment]
This issue should be fixed with switching to MegaMenus
