### ISSUE TITLE
/vshop create minecraft:villager (And various) spawns in infinite entities without stopping

### ISSUE THREAD

**Issue by Saisinclare** [DosMike/VillagerShops#52]
When I do /vshop create minecraft:villager, it spawns in infinite  amount of npcs ranging between chatting npcs and trainers.  here's a gif of the problem. [https://gfycat.com/RegalPossibleKiskadee](url)

I followed the youtube video and I'm sure I might have missed something, but, i'm not sure what to do.

I forgot to record this too, but when I spawn in a pixelmon:chattingNPC or anything pixelmon related, it disappears.  I had checked the config and it makes it an air block instead.

**Comment by DosMike** [comment]
VillagerShops is incompatible with Pixelmon. 
Pixelmon replaces all minecraft:villagers with trainers/Pixelmon NPCs. This results in VillagerShops loosing track of the mobs and thinking the mob died it respawns the "missing" mob, resulting in this spam.
I know that a lot of Pixelmon server are looking at this plugin but I do not have the time or interest to fix such a specific bug.
Please try to stick with Pixelmon Mob where possible or use a different shop plugin. 
If you are or know someone that knows how to write plugins you are free to send me a pull request with a fix.

I'll add a notice to the downloads warning other users about this issue
