### ISSUE TITLE
[Bug] Free items

### ISSUE THREAD

**Issue by Meta-Win** [DosMike/VillagerShops#53]
When you click to buy something, and press "e" to open and close your inventory repeatedly, you get some items from the shop(In this case, flux sponge and 1k Me Storage Component)

Vídeo: https://www.youtube.com/watch?v=7fjPZqfcgE0

**Comment by DosMike** [comment]
Could you please upload your modlist to pastebin

**Comment by Meta-Win** [comment]
https://pastebin.com/N0aMTUMY

**Comment by DosMike** [comment]
Did you check if this problem is related to issue #51. 
Remove InventoryTweaks from the server if you have it on there, it's a client mod.

**Comment by Meta-Win** [comment]
InventoryTweaks isn't on the server

**Comment by DosMike** [comment]
This issue should be fixed with switching to MegaMenus
