### ISSUE TITLE
What is anti-Glitch system and how do i disable it?

### ISSUE THREAD

**Issue by ApolloMCC** [DosMike/VillagerShops#56]
Title

**Comment by DosMike** [comment]
Please read the descriptions and configs of plugins you install. (In this case it's in the mega menus config)

Not to sound rude, but I really don't want to explain everything over and over.

**Comment by ApolloMCC** [comment]
Thank you Dos, i just didn't know where to find the information, idiot me thought that that message was coming from villagershops.
