### ISSUE TITLE
Error while clicking on Villager

### ISSUE THREAD

**Issue by TheRealDadbeard** [DosMike/VillagerShops#57]
https://pastebin.com/8BQqBUzg
spongeforge-1.12.2-2838-7.1.7-RC3832

Clicking on a Villager opens up the vanilla gui then spits this error out in the server console

**Comment by DosMike** [comment]
This is an incompatibility with galacticraft, probably similar to https://github.com/DosMike/MegaMenus/issues/3.

Please provide full information (`/sponge version`, modlist/plugins with version, other things that might be relevant)

**Comment by TheRealDadbeard** [comment]
there you go https://pastebin.com/UDZij7w2

**Comment by dwightdurmon** [comment]
It also occurs with spongeforge-1.12.2-2838-7.1.7-RC3838.  Same error message.

**Comment by DosMike** [comment]
Should be fixed with the next release
