### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by pedrodalben** [DosMike/VillagerShops#64]
When I restart the server the entities become minecraft entities.
already tried to reinstall

**Comment by Zoneman1972** [comment]
I am having this same issue now. I have set up the shops and they all work perfectly until server restarts and then they are all reverted to normal villagers but still retaining the shop name they were given.
Running Forge 1.12.2-14.23.5.2838
SpongeForge 1.12.2-2838-7.1.7-RC3900
VillagerShops 1.9.1

Using this plugin with the Sevtech Ages 3.1.2 modpack.
