### ISSUE TITLE
Pixelmon compatibility 

### ISSUE THREAD

**Issue by erposse90** [DosMike/VillagerShops#70]
Is it possible to have a version compatible with pixelmon reforge?  This plugin is essential now that pixelmon merchants cannot be edited!

**Comment by DosMike** [comment]
The incompatibility with pixelmon is not that critical, as described in the setup guide for villager shops:
> **What’s the Problem:** Pixelmon by default is replacing Villagers with trainers. While this is all fine in most cases, this will make VillagerShops loose track of the entity. As a reaction VillagerShop spawns a new villager, that gets converted the next tick.
> **Solutions**: You can either not use any Villagers as shops (other animals / mobs should be fine), or go into your Pixelmon config and disable villager conversion.

**Comment by erposse90** [comment]
Ok, it works, but only with some pixelmon npc, why? For example if I choose the npc shopkeeper, it generates an invisible npc,why?anyway  great plugin!

**Comment by DosMike** [comment]
Idk, I can only imagine that some entites are missing information when villagershop spawns them (like a career type info or something). But i can't automatically get that. Also I really don't have the time to manually go through mods to make them 100% compatible, so it is what it is.

**Comment by erposse90** [comment]
Ok, I thought I was doing something wrong xD
