### ISSUE TITLE
Can't create shop with minecraft:villager

### ISSUE THREAD

**Issue by ange-black69** [DosMike/VillagerShops#71]
Hello,
Plugin version : 2.5
I've got the permission : vshop.create.minecraft.villager

However, when creating a shop with the command : vshop create minecraft:villager I got the following error : Argument EntityType may have only one value !

It works four every other type of entity like sponge:human or modded one.

Any idea ?
Thank you

**Comment by DosMike** [comment]
was fixed with SpongeAPI [#2109](https://github.com/SpongePowered/SpongeAPI/issues/2109).
Please wait for the release of Sponge 7.2.1.
If you're OK with instable builds update to SpongeForge 1.12.2-2838-7.2.1-RC4013 or later or SpongeVanilla 1.12.2-7.2.1-RC350 or later
