### ISSUE TITLE
Compatibility with Too Much Stock API ?

### ISSUE THREAD

**Issue by ange-black69** [DosMike/VillagerShops#72]
Hello,
I was wondering if you plan eventually to implement your own api : too much stock into this plugin?
Will be really awesome to have admin shops prices based on supply and demands !
Cheers,

**Comment by DosMike** [comment]
that was the point. currently I'm cleaning up some existing code in this plugin to hopefully make the other task easier.

**Comment by ange-black69** [comment]
Well thank you very much !
