### ISSUE TITLE
Shops stop working when clicked on with an item.

### ISSUE THREAD

**Issue by IShallNot** [DosMike/VillagerShops#74]
As the title says, whenever I click on a shop with an item in my hand they all stop working.

**Comment by IShallNot** [comment]
It also does not fix itself until the server has been restarted.

**Comment by DosMike** [comment]
If no player can access shops you mod pack most likely contains Potion Core, please read the Setup Guide.
If some players can access shops or players can only access shops once, you might want to try and disable the anti-glitch system in MegaMenus config.
