### ISSUE TITLE
I had a problem with villagershops, spongeforge, forge, and my mod pack, is it something im doing?

### ISSUE THREAD

**Issue by ChrisYoungPlus** [DosMike/VillagerShops#79]
[16:39:22] [Server thread/WARN] [Sponge]: /***************************************************************************************************************************************************/
> [16:39:22] [Server thread/WARN] [Sponge]: /*                                               Could not pass  ClickInventoryEvent$Secondary$Impl                                                */
> [16:39:22] [Server thread/WARN] [Sponge]: /***************************************************************************************************************************************************/
> [16:39:22] [Server thread/WARN] [Sponge]: /* Could not pass the event ClickInventoryEvent$Secondary$Impl to an Event Listener!                                                               */
> [16:39:22] [Server thread/WARN] [Sponge]: /*                                                                                                                                                 */
> [16:39:22] [Server thread/WARN] [Sponge]: /* Since the event can be modified during the event's listener,                                                                                    */
> [16:39:22] [Server thread/WARN] [Sponge]: /* there could be adverse side effects of the exception occurring                                                                                  */
> [16:39:22] [Server thread/WARN] [Sponge]: /* such that duplications or other game breaking issues could exist.                                                                               */
> [16:39:22] [Server thread/WARN] [Sponge]: /*                                                                                                                                                 */
> [16:39:22] [Server thread/WARN] [Sponge]: /* Due to the nature of the exception, this is not likely an exception                                                                             */
> [16:39:22] [Server thread/WARN] [Sponge]: /* that is covered by SpongeForge or Forge itself, and therefore should                                                                            */
> [16:39:22] [Server thread/WARN] [Sponge]: /* be reported to the mod/plugin author first prior to reporting to                                                                                */
> [16:39:22] [Server thread/WARN] [Sponge]: /* Sponge or Forge.                                                                                                                                */
> [16:39:22] [Server thread/WARN] [Sponge]: /*                                                                                                                                                 */
> [16:39:22] [Server thread/WARN] [Sponge]: /* Owning Mod/Plugin: megamenus                                                                                                                    */
> [16:39:22] [Server thread/WARN] [Sponge]: /* Exception:                                                                                                                                      */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.lang.NullPointerException: null                                                                                                        */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:266)                                                                        */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.data.property.store.item.HarvestingPropertyStore.getFor(HarvestingPropertyStore.java:50)                           */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.data.property.store.common.AbstractItemStackPropertyStore.getFor(AbstractItemStackPropertyStore.java:43)           */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.data.property.PropertyStoreDelegate.getFor(PropertyStoreDelegate.java:48)                                          */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.data.property.SpongePropertyRegistry.getPropertiesFor(SpongePropertyRegistry.java:126)                             */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     net.minecraft.item.ItemStack.getApplicableProperties(ItemStack.java:1906)                                                                   */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.registry.type.item.ItemStackComparatorRegistryModule$Properties.compare(ItemStackComparatorRegistryModule.java:76) */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.registry.type.item.ItemStackComparatorRegistryModule$Properties.compare(ItemStackComparatorRegistryModule.java:72) */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:217)                                                                   */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:216)                                                                   */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:216)                                                                   */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     de.dosmike.sponge.vshop.shops.StockItem.lambda$filterInventory$6(StockItem.java:247)                                                        */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.item.inventory.query.operation.ItemStackCustomOperation.matches(ItemStackCustomOperation.java:40)                  */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.item.inventory.query.operation.ItemStackCustomOperation.matches(ItemStackCustomOperation.java:32)                  */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.item.inventory.query.operation.ItemStackQueryOperation.matches(ItemStackQueryOperation.java:49)                    */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.item.inventory.query.Query.matches(Query.java:123)                                                                 */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.item.inventory.query.Query.depthFirstSearch(Query.java:107)                                                        */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.item.inventory.query.Query.execute(Query.java:78)                                                                  */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.item.inventory.query.Query.execute(Query.java:70)                                                                  */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.item.inventory.adapter.impl.DefaultImplementedAdapterInventory.query(DefaultImplementedAdapterInventory.java:243)  */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     de.dosmike.sponge.vshop.shops.StockItem.filterInventory(StockItem.java:247)                                                                 */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     de.dosmike.sponge.vshop.shops.StockItem.invSupply(StockItem.java:539)                                                                       */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     de.dosmike.sponge.vshop.shops.StockItem.sell(StockItem.java:447)                                                                            */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     de.dosmike.sponge.vshop.shops.InteractionHandler.shopItemClicked(InteractionHandler.java:99)                                                */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     de.dosmike.sponge.vshop.menus.MShop.lambda$new$2(MShop.java:79)                                                                             */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     de.dosmike.sponge.vshop.menus.MShop.fireClickEvent(MShop.java:98)                                                                           */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     de.dosmike.sponge.megamenus.impl.GuiRenderer.interactHandler(GuiRenderer.java:174)                                                          */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     de.dosmike.sponge.megamenus.impl.GuiRenderer.access$000(GuiRenderer.java:48)                                                                */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     de.dosmike.sponge.megamenus.impl.GuiRenderer$1.lambda$null$4(GuiRenderer.java:93)                                                           */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)                                                                     */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)                                                                   */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)                                                                   */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)                                                              */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)                                                                       */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)                                                                */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)                                                               */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)                                                         */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)                                                                       */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)                                                                      */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     de.dosmike.sponge.megamenus.impl.GuiRenderer$1.lambda$null$5(GuiRenderer.java:93)                                                           */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.util.Optional.ifPresent(Optional.java:159)                                                                                             */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     de.dosmike.sponge.megamenus.impl.GuiRenderer$1.lambda$$6(GuiRenderer.java:88)                                                               */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.item.inventory.custom.CustomInventoryListener.handle(CustomInventoryListener.java:63)                              */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.item.inventory.custom.CustomInventoryListener.handle(CustomInventoryListener.java:40)                              */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:97)                                                        */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383)                                                      */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:458)                                              */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:419)                                                      */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:467)                                                         */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:249)                                                                          */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.event.tracking.phase.packet.inventory.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:250)         */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.event.tracking.phase.packet.inventory.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:64)          */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:317)                                                   */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:618)                                                           */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:221)                              */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     net.minecraft.network.PacketThreadUtil$1.redirect$zlk000$impl$redirectToPhaseTracker(SourceFile:540)                                        */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)                                                                                 */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                                                     */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                    */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     net.minecraft.util.Util.func_181617_a(SourceFile:529)                                                                                       */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:308)                                                            */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     net.minecraft.server.MinecraftServer.redirect$zjo000$onRun(MinecraftServer.java:4682)                                                       */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)                                                                 */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)                                                       */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                                                 */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                                          */
> [16:39:22] [Server thread/WARN] [Sponge]: /*     java.lang.Thread.run(Thread.java:748)                                                                                                       */
> [16:39:22] [Server thread/WARN] [Sponge]: /***************************************************************************************************************************************************/

**Comment by DosMike** [comment]
This is not helpful at all.
Please include the following information whenever you report errors:
* What happened/broke
* How can that be replicated
* Include all mods and server version (you can get the version with `/sponge version`)
* Upload the full latest.log to a gist or unlisted paste (DO NOT paste the log into your report and don't attach the logfile to your issue. That just makes it unreadable on mobile)
* Give any additional information that might help solve the issue

**Comment by DosMike** [comment]
i'll assume this was resolved through updating
