### ISSUE TITLE
I Cannot Right Click the Shop

### ISSUE THREAD

**Issue by AdriPlaysz** [DosMike/VillagerShops#80]
I cannot open the Shop!
-I have set the price
-I have installed LangSwitch
-I have installed MegaMenus
Why can't I open my Shops is this a bug?

**Comment by DosMike** [comment]
If no player can access shops you mod pack most likely contains Potion Core, please read the Setup Guide.
If some players can access shops or players can only access shops once, you might want to try and disable the anti-glitch system in MegaMenus config.
