### ISSUE TITLE
Shops can be created on other Claims

### ISSUE THREAD

**Issue by Mareron** [DosMike/VillagerShops#82]
Heyho,

I have noticed that you can set up Player vShops on chests in claims that you are not the owner of.
So you can basically steal from claimed chests by creating a shopkeeper, adding some Items to the shopkeeper (more or less a guessing game) and then buy the items out of the claimed chest.

Could you add a check for Claims and/or Trust on said claims (we are using GriefDefender) when creating and re-linking a Playershop?
Maybe an Admin Override permission (so someone with the permission can create shops anywhere)

Kind Regards,
LordMareron

**Comment by DosMike** [comment]
It should be possible, I just need to get GD to compile properly

**Comment by DosMike** [comment]
i added basic GD, RP and UG2 integration with [integration/protection](/DosMike/VillagerShops/tree/integration/protection), please take a look at the [new config options](https://github.com/DosMike/VillagerShops/blob/e1376ec6cdc41b3ccec00f42c492a291a43e7090/src/main/resources/assets/vshop/default_settings.conf#L46) and tell me if that's what you had in mind.

I still need to test things, then i can potentially push an update.
