### ISSUE TITLE
Problem with shops

### ISSUE THREAD

**Issue by chwastabuser** [DosMike/VillagerShops#83]
im using villager shops on pixelmon server with ecobridge , economy light , lang switch and megamenus.
there are only one problem. Its hard to explain , so i drop a screenshot.
![Screenshot_4](https://user-images.githubusercontent.com/69573594/89986488-eee10080-dc7c-11ea-9adb-0e589434f477.png)
![Screenshot_5](https://user-images.githubusercontent.com/69573594/89986502-f30d1e00-dc7c-11ea-94e0-5badfeab24e2.png)
![Screenshot_6](https://user-images.githubusercontent.com/69573594/89986513-f6080e80-dc7c-11ea-8c92-923e5dbe1097.png)

**Comment by Mareron** [comment]
I'm not the dev, so this is just a guess but I'm pretty sure that this is caused by either a broken or missing language file

**Comment by DosMike** [comment]
correct, the setup guide on ore tells you what to do in this case
